name: Main build

on:
  push:
    branches: [main]

env:
  REGISTRY: ghcr.io
  NAMESPACE: galasa-dev
  IMAGE_TAG: main

jobs:
  build-cli:
    name: Build the Galasa CLI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout CLI
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.9.2

      # Pull down dependencies with Gradle and put them in the right places.
      - name: Gather dependencies using Gradle
        run : |
          gradle -b build.gradle installJarsIntoTemplates --info \
          -PsourceMaven=https://development.galasa.dev/gh/maven-repo/maven \
          -PcentralMaven=https://repo.maven.apache.org/maven2/ \
          -PtargetMaven=${{ github.workspace }}/repo \

      # Generate client code so galasactl can communicate with the API server.
      - name: Generate Go client code using openapi.yaml
        run : |
          docker run --rm -v ${{ github.workspace }}:/var/workspace ghcr.io/galasa-dev/openapi:main java -jar /opt/openapi/openapi-generator-cli.jar generate -i /var/workspace/build/dependencies/openapi.yaml -g go -o /var/workspace/pkg/galasaapi --additional-properties=packageName=galasaapi --global-property=apiTests=false

      # The go.mod and go.sum are out of date, as they do not include the generated code so they are deleted here. They get re-generated when we compile.
      # Due to permissions, deleting the go.mod and go.sum must be done by the openapi image as the image generated those files.

      - name: Clear go.mod
        run : |
          docker run --rm -v ${{ github.workspace }}:/var/workspace ghcr.io/galasa-dev/openapi:main rm /var/workspace/pkg/galasaapi/go.mod

      - name: Clear go.sum
        run : |
          docker run --rm -v ${{ github.workspace }}:/var/workspace ghcr.io/galasa-dev/openapi:main rm /var/workspace/pkg/galasaapi/go.sum

      # The go code needs to know which version of Galasa it is part of, so substitute an eye-catcher with the correct value.
      - name: Update version 
        run : |
          version=$(cat VERSION) &&
          cat pkg/cmd/root.go | sed "s/unknowncliversion-unknowngithash/${version}/1" > temp.txt &&
          mv -f temp.txt pkg/cmd/root.go &&
          cat pkg/cmd/root.go

      # Invoke the make command to build the go code, run unit tests and gather code coverage stats.
      - name: Build Go code with the Makefile
        run : |
          make all

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'semeru'
          cache: maven

      - name: Chmod local test script
        run: | 
          chmod +x test-galasactl-local.sh

      - name: Run local test script with Maven
        run : |
          ./test-galasactl-local.sh --buildTool maven

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 6.9.2

      - name: Run local test script with Gradle
        run : |
          ./test-galasactl-local.sh --buildTool gradle

      # Commenting out for now as we cannot reach the prod1 ecosystem from GitHub Actions.
      # - name: Chmod ecosystem test script
      #   run : |
      #     chmod +x test-galasactl-ecosystem.sh

      # - name: Run ecosystem test script
      #   run : |
      #     ./test-galasactl-ecosystem.sh --bootstrap https://prod1-galasa-dev.cicsk8s.hursley.ibm.com/api/bootstrap

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Extract metadata for galasactl image
        id: metadata-galasactl
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/galasactl-x86_64
  
      - name: Build galasactl image
        id: build-galasactl
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/dockerfile.galasactl
          push: true
          tags: ${{ steps.metadata-galasactl.outputs.tags }}
          labels: ${{ steps.metadata-galasactl.outputs.labels }}
          build-args: |
            platform=linux-x86_64

      - name: Extract metadata for galasactl-ibm image
        id: metadata-galasactl-ibm
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/galasactl-ibm-x86_64
  
      - name: Build galasactl-ibm image
        id: build-galasactl-ibm
        uses: docker/build-push-action@v5
        with:
          context: dockerfiles/certs
          file: dockerfiles/dockerfile.galasactl-ibm
          push: true
          tags: ${{ steps.metadata-galasactl-ibm.outputs.tags }}
          labels: ${{ steps.metadata-galasactl-ibm.outputs.labels }}
          build-args: |
            dockerRepository=ghcr.io
            tag=main

      - name: Extract metadata for galasactl-executables image
        id: metadata-galasactl-executables
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/galasactl-executables
  
      - name: Build galasactl-executables image
        id: build-galasactl-executables
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfiles/dockerfile.galasactl-executables
          push: true
          tags: ${{ steps.metadata-galasactl-executables.outputs.tags }}
          labels: ${{ steps.metadata-galasactl-executables.outputs.labels }}

      - name: Recycle application in ArgoCD
        env: 
            ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: |
            docker run --env ARGOCD_AUTH_TOKEN=${{ env.ARGOCD_AUTH_TOKEN }} --rm -v ${{ github.workspace }}:/var/workspace ghcr.io/galasa-dev/argocdcli:main app actions run gh-cli restart --kind Deployment --resource-name cli-gh --server argocd.galasa.dev
       
      - name: Wait for application health in ArgoCD
        env: 
            ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_TOKEN }}
        run: |
            docker run --env ARGOCD_AUTH_TOKEN=${{ env.ARGOCD_AUTH_TOKEN }} --rm -v ${{ github.workspace }}:/var/workspace ghcr.io/galasa-dev/argocdcli:main app wait gh-cli --resource apps:Deployment:cli-gh --health --server argocd.galasa.dev
       